### ISSUE TITLE
can't install some packages, such as survminer

### ISSUE THREAD

**Issue by xh542428798** [hvalev/shiny-server-arm-docker#61]
~~checking for cmake... no~~

------------------ CMAKE NOT FOUND --------------------

~~CMake was not found on the PATH. Please install CMake:~~

 ~~- sudo yum install cmake          (Fedora/CentOS; inside a terminal)~~
 ~~- sudo apt install cmake          (Debian/Ubuntu; inside a terminal).~~
 ~~- sudo pacman -S cmake            (Arch Linux; inside a terminal).~~
 ~~- sudo brew install cmake         (MacOS; inside a terminal with Homebrew)~~
 ~~- sudo port install cmake         (MacOS; inside a terminal with MacPorts)~~

~~Alternatively install CMake from: <https://cmake.org/> ~~

OK, I solved it, i just type wrong "apt-get install cmake", it just""apt install cmake", then I installed cmake successfully.
Thanks.

**Comment by hvalev** [comment]
Alright, I'm closing this issue
