### ISSUE TITLE
Unresponsive Shiny App on Mobile

### ISSUE THREAD

**Issue by the-robbie** [hvalev/shiny-server-arm-docker#73]
I'm hosting a Shiny app I created using this docker container. This works really well since I'm hosting it from my Raspberry Pi and I was unable to implement it using [openanalytics/shinyproxy](https://github.com/openanalytics/shinyproxy) as that doesn't appear to work using a Raspberry Pi. I was very excited when I found this and when using a computer's web browser, the app works flawlessly.

The only issue is that it is very unresponsive and practically unusable from a mobile browser. The hello app that comes preloaded seems to work fine on mobile, but that is a much simpler app. It seems that there was/is a similar issue on the openanalytics/shinyproxy version and a workaround was discovered that can be found [here](https://github.com/openanalytics/shinyproxy/issues/307). Unfortunately, the workaround doesn't quite translate 1:1 from that version to this version.

Is there a way to make my app more responsive on mobile using this version of shiny-server for ARM devices? Please let me know if you need more information from me to help find a fix. Much appreciated!

**Comment by hvalev** [comment]
Take this with a grain of salt as I've just glanced over this, but I believe that shinyproxy, among others, provides some overlays and gives you control on how apps are being rendered using their templates. Those templates are unfortunately not available in this repository and it only includes shiny-server. So you cannot really use the solution you linked as their source is not available in this repository. Some tips for troubleshooting this are:
1) Have you tried to compare the performance of your app (not the hello world one) on both desktop and mobile?
2) Have you tried different mobile browsers?

**Comment by deshpande-prasanna** [comment]
Hello,

I am trying to do a google drive authentication using a .secrets directory. I put the .secrets directory under my application directory and tried to point to it in the cache options of googledrive something like below

googledrive::drive_auth(cache='/srv/shiny-server/myApp/.secrets', email = TRUE)

but doesn't seem to work.. error says can't get google credentials. 

could you please help me how to set this up.
